// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRTx-pndZ_ogYINQvQBVhmS00IWUekpuY',
    appId: '1:926460402818:android:c58a548b687a951d78689b',
    messagingSenderId: '926460402818',
    projectId: 'insurease-8bfa5',
    databaseURL: 'https://insurease-8bfa5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'insurease-8bfa5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDusu5CBnfO8YQUj1pgp3FOgtMAWyOGn8Q',
    appId: '1:926460402818:ios:7ce59c6128e2e10278689b',
    messagingSenderId: '926460402818',
    projectId: 'insurease-8bfa5',
    databaseURL: 'https://insurease-8bfa5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'insurease-8bfa5.appspot.com',
    iosClientId: '926460402818-gslsjsrc9dj60f2gv7erb953siunmmd9.apps.googleusercontent.com',
    iosBundleId: 'com.example.insurease',
  );
}
